ch10: ch10.c csapp.o
	gcc ch10.c csapp.o -o ch10

kill: kill.c csapp.o
	gcc kill.c csapp.o -o kill

sh: shellex.c csapp.o
	gcc shellex.c csapp.o -o sh
	
snooze: snooze.c csapp.o
	gcc snooze.c csapp.o -o snooze

myecho: myecho.c
	gcc myecho.c -o myecho
	
csapp.o: csapp.c
	gcc -c csapp.c

ch8: ch8.c
	gcc ch8.c -o ch8


clean:
	rm *.o ch10
